package resources

import (
	"fmt"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"

	objectstoragev1alpha1 "github.com/openeverest/seaweedfs-operator/api/v1alpha1"
)

const (
	filerConfigVolumeName = "filer-config"
	filerConfigMountPath  = "/etc/seaweedfs"
)

func defaultFilerStorage() objectstoragev1alpha1.StorageSpec {
	return objectstoragev1alpha1.StorageSpec{
		Size:        resource.MustParse("5Gi"),
		AccessModes: []corev1.PersistentVolumeAccessMode{corev1.ReadWriteOnce},
	}
}

func FilerStorage(cluster *objectstoragev1alpha1.ObjectStorageCluster) objectstoragev1alpha1.StorageSpec {
	if cluster.Spec.Filer.Storage != nil {
		return *cluster.Spec.Filer.Storage
	}
	return defaultFilerStorage()
}

func FilerTOML(cluster *objectstoragev1alpha1.ObjectStorageCluster) string {
	return fmt.Sprintf(`# Generated by seaweedfs-operator for %s/%s. Do not edit by hand:
# the operator overwrites this ConfigMap on every reconcile. To supply your own
# configuration set spec.filer.configMapName on the ObjectStorageCluster.

[leveldb2]
enabled = true
dir = "%s/filerldb2"
`, cluster.Namespace, cluster.Name, DataMountPath)
}

func FilerConfigMap(cluster *objectstoragev1alpha1.ObjectStorageCluster) *corev1.ConfigMap {
	return &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{
			Name:      FilerConfigMapName(cluster),
			Namespace: cluster.Namespace,
			Labels:    Labels(cluster, ComponentFiler),
		},
		Data: map[string]string{
			"filer.toml": FilerTOML(cluster),
		},
	}
}

func FilerArgs(cluster *objectstoragev1alpha1.ObjectStorageCluster) []string {
	f := cluster.Spec.Filer
	args := []string{
		"filer",
		flag("ip", fmt.Sprintf("$(POD_NAME).%s.%s.svc.cluster.local", HeadlessServiceName(cluster, ComponentFiler), cluster.Namespace)),
		flag("ip.bind", "0.0.0.0"),
		flag("port", FilerHTTPPort),
		flag("master", MasterEndpoint(cluster)),
		flag("defaultReplicaPlacement", cluster.Spec.DefaultReplication),
		flag("maxMB", f.MaxMB),
	}
	if cluster.Spec.Metrics {
		args = append(args, flag("metricsPort", MetricsPort))
	}
	return args
}

func FilerStatefulSet(cluster *objectstoragev1alpha1.ObjectStorageCluster) *appsv1.StatefulSet {
	sts := statefulSetSkeleton(cluster, ComponentFiler, cluster.Spec.Filer.Replicas)

	configMap := cluster.Spec.Filer.ConfigMapName
	if configMap == "" {
		configMap = FilerConfigMapName(cluster)
	}

	sts.Spec.Template = buildPodTemplate(podTemplateOptions{
		cluster:   cluster,
		component: ComponentFiler,
		overrides: cluster.Spec.Filer.PodOverrides,
		args:      FilerArgs(cluster),
		httpPort:  FilerHTTPPort,
		probePath: "/healthz",
		ports: []corev1.ContainerPort{
			{Name: "http", ContainerPort: FilerHTTPPort, Protocol: corev1.ProtocolTCP},
			{Name: "grpc", ContainerPort: FilerGRPCPort, Protocol: corev1.ProtocolTCP},
		},
		mountData: true,
		extraVolumes: []corev1.Volume{{
			Name: filerConfigVolumeName,
			VolumeSource: corev1.VolumeSource{
				ConfigMap: &corev1.ConfigMapVolumeSource{
					LocalObjectReference: corev1.LocalObjectReference{Name: configMap},
				},
			},
		}},
		extraMounts: []corev1.VolumeMount{{
			Name:      filerConfigVolumeName,
			MountPath: filerConfigMountPath,
		}},
		annotations: map[string]string{
			"objectstorage.openeverest.io/filer-config-hash": HashString(FilerTOML(cluster)),
		},
	})

	sts.Spec.VolumeClaimTemplates = []corev1.PersistentVolumeClaim{
		dataVolumeClaim(cluster, ComponentFiler, FilerStorage(cluster)),
	}
	return sts
}

func FilerHeadlessService(cluster *objectstoragev1alpha1.ObjectStorageCluster) *corev1.Service {
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      HeadlessServiceName(cluster, ComponentFiler),
			Namespace: cluster.Namespace,
			Labels:    Labels(cluster, ComponentFiler),
		},
		Spec: corev1.ServiceSpec{
			ClusterIP:                corev1.ClusterIPNone,
			PublishNotReadyAddresses: true,
			Selector:                 SelectorLabels(cluster, ComponentFiler),
			Ports: []corev1.ServicePort{
				{Name: "http", Port: FilerHTTPPort, TargetPort: intstr.FromInt32(FilerHTTPPort)},
				{Name: "grpc", Port: FilerGRPCPort, TargetPort: intstr.FromInt32(FilerGRPCPort)},
			},
		},
	}
}

func FilerClientService(cluster *objectstoragev1alpha1.ObjectStorageCluster) *corev1.Service {
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name:      ClientServiceName(cluster, ComponentFiler),
			Namespace: cluster.Namespace,
			Labels:    Labels(cluster, ComponentFiler),
		},
		Spec: corev1.ServiceSpec{
			Type:     corev1.ServiceTypeClusterIP,
			Selector: SelectorLabels(cluster, ComponentFiler),
			Ports: []corev1.ServicePort{
				{Name: "http", Port: FilerHTTPPort, TargetPort: intstr.FromInt32(FilerHTTPPort)},
				{Name: "grpc", Port: FilerGRPCPort, TargetPort: intstr.FromInt32(FilerGRPCPort)},
			},
		},
	}
}
