---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seaweedfs-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstorage.openeverest.io
  resources:
  - objectstoragebuckets
  - objectstorageclusters
  - objectstorageusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstorage.openeverest.io
  resources:
  - objectstoragebuckets/finalizers
  - objectstorageclusters/finalizers
  - objectstorageusers/finalizers
  verbs:
  - update
- apiGroups:
  - objectstorage.openeverest.io
  resources:
  - objectstoragebuckets/status
  - objectstorageclusters/status
  - objectstorageusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
