//go:build !ignore_autogenerated

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *BucketGrant) DeepCopyInto(out *BucketGrant) {
	*out = *in
	if in.BucketRef != nil {
		in, out := &in.BucketRef, &out.BucketRef
		*out = new(LocalSecretReference)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]S3Action, len(*in))
		copy(*out, *in)
	}
}

func (in *BucketGrant) DeepCopy() *BucketGrant {
	if in == nil {
		return nil
	}
	out := new(BucketGrant)
	in.DeepCopyInto(out)
	return out
}

func (in *BucketQuota) DeepCopyInto(out *BucketQuota) {
	*out = *in
}

func (in *BucketQuota) DeepCopy() *BucketQuota {
	if in == nil {
		return nil
	}
	out := new(BucketQuota)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *FilerSpec) DeepCopyInto(out *FilerSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.PodOverrides.DeepCopyInto(&out.PodOverrides)
}

func (in *FilerSpec) DeepCopy() *FilerSpec {
	if in == nil {
		return nil
	}
	out := new(FilerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

func (in *MasterSpec) DeepCopyInto(out *MasterSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.PodOverrides.DeepCopyInto(&out.PodOverrides)
}

func (in *MasterSpec) DeepCopy() *MasterSpec {
	if in == nil {
		return nil
	}
	out := new(MasterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageBucket) DeepCopyInto(out *ObjectStorageBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ObjectStorageBucket) DeepCopy() *ObjectStorageBucket {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucket)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ObjectStorageBucketList) DeepCopyInto(out *ObjectStorageBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectStorageBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ObjectStorageBucketList) DeepCopy() *ObjectStorageBucketList {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucketList)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ObjectStorageBucketSpec) DeepCopyInto(out *ObjectStorageBucketSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(BucketQuota)
		**out = **in
	}
}

func (in *ObjectStorageBucketSpec) DeepCopy() *ObjectStorageBucketSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucketSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageBucketStatus) DeepCopyInto(out *ObjectStorageBucketStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
}

func (in *ObjectStorageBucketStatus) DeepCopy() *ObjectStorageBucketStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageBucketStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageCluster) DeepCopyInto(out *ObjectStorageCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ObjectStorageCluster) DeepCopy() *ObjectStorageCluster {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ObjectStorageClusterList) DeepCopyInto(out *ObjectStorageClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectStorageCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ObjectStorageClusterList) DeepCopy() *ObjectStorageClusterList {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ObjectStorageClusterSpec) DeepCopyInto(out *ObjectStorageClusterSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]LocalSecretReference, len(*in))
		copy(*out, *in)
	}
	in.Master.DeepCopyInto(&out.Master)
	in.Volume.DeepCopyInto(&out.Volume)
	in.Filer.DeepCopyInto(&out.Filer)
	in.S3.DeepCopyInto(&out.S3)
	out.Upgrade = in.Upgrade
}

func (in *ObjectStorageClusterSpec) DeepCopy() *ObjectStorageClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageClusterStatus) DeepCopyInto(out *ObjectStorageClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Master = in.Master
	out.Volume = in.Volume
	out.Filer = in.Filer
	out.S3 = in.S3
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(TopologyStatus)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ObjectStorageClusterStatus) DeepCopy() *ObjectStorageClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageUser) DeepCopyInto(out *ObjectStorageUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ObjectStorageUser) DeepCopy() *ObjectStorageUser {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageUser)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ObjectStorageUserList) DeepCopyInto(out *ObjectStorageUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ObjectStorageUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ObjectStorageUserList) DeepCopy() *ObjectStorageUserList {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageUserList)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ObjectStorageUserSpec) DeepCopyInto(out *ObjectStorageUserSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.BucketGrants != nil {
		in, out := &in.BucketGrants, &out.BucketGrants
		*out = make([]BucketGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClusterActions != nil {
		in, out := &in.ClusterActions, &out.ClusterActions
		*out = make([]S3Action, len(*in))
		copy(*out, *in)
	}
}

func (in *ObjectStorageUserSpec) DeepCopy() *ObjectStorageUserSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageUserSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ObjectStorageUserStatus) DeepCopyInto(out *ObjectStorageUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GrantedBuckets != nil {
		in, out := &in.GrantedBuckets, &out.GrantedBuckets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ObjectStorageUserStatus) DeepCopy() *ObjectStorageUserStatus {
	if in == nil {
		return nil
	}
	out := new(ObjectStorageUserStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *PodOverrides) DeepCopyInto(out *PodOverrides) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraEnv != nil {
		in, out := &in.ExtraEnv, &out.ExtraEnv
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

func (in *PodOverrides) DeepCopy() *PodOverrides {
	if in == nil {
		return nil
	}
	out := new(PodOverrides)
	in.DeepCopyInto(out)
	return out
}

func (in *S3Spec) DeepCopyInto(out *S3Spec) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	in.PodOverrides.DeepCopyInto(&out.PodOverrides)
}

func (in *S3Spec) DeepCopy() *S3Spec {
	if in == nil {
		return nil
	}
	out := new(S3Spec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.VolumeMode != nil {
		in, out := &in.VolumeMode, &out.VolumeMode
		*out = new(v1.PersistentVolumeMode)
		**out = **in
	}
}

func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TopologyFromNodeLabels) DeepCopyInto(out *TopologyFromNodeLabels) {
	*out = *in
}

func (in *TopologyFromNodeLabels) DeepCopy() *TopologyFromNodeLabels {
	if in == nil {
		return nil
	}
	out := new(TopologyFromNodeLabels)
	in.DeepCopyInto(out)
	return out
}

func (in *TopologyStatus) DeepCopyInto(out *TopologyStatus) {
	*out = *in
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
}

func (in *TopologyStatus) DeepCopy() *TopologyStatus {
	if in == nil {
		return nil
	}
	out := new(TopologyStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *UpgradePolicy) DeepCopyInto(out *UpgradePolicy) {
	*out = *in
}

func (in *UpgradePolicy) DeepCopy() *UpgradePolicy {
	if in == nil {
		return nil
	}
	out := new(UpgradePolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *VolumeSpec) DeepCopyInto(out *VolumeSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.TopologyFromNodeLabels != nil {
		in, out := &in.TopologyFromNodeLabels, &out.TopologyFromNodeLabels
		*out = new(TopologyFromNodeLabels)
		**out = **in
	}
	in.PodOverrides.DeepCopyInto(&out.PodOverrides)
}

func (in *VolumeSpec) DeepCopy() *VolumeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeSpec)
	in.DeepCopyInto(out)
	return out
}
